### PR TITLE
New [WIP]

### PR DESCRIPTION
**Pull request by thongphp**
- [x] Only allow admin can see configuration view.
- [x] Dropzone validate file before upload
- [x] Rewrite process for add/remove scenes in tour edit view.
- [x] Move tour edit into individual view
- [x] Move user edit into individual view (Include upload logo and change)
- [ ] Move scene edit into individual view
- [x] Re-write Hotspot layout, move to individual view
- [x] Add dropzone.js support
- [x] JS file validate with post_max & max_file_size
- [x] Move scene upload to separate request that allow we upload much more
- [x] Add configuration view
- [x] Move configuration to navigate bar and make sure only shown for admin ( by user name && id == 1) only
- [ ] Tour skin-settings ( xml ) in scene view
- [ ] Tooltip for each input to make better UX
- [ ] Move hotspots editing to sidebar - right. We'll need refactor current HTML structure. After that we can enable WYSIWYG back.
- [ ] [Improve][Not required] XML Editor
- [ ] Drag / Drop ordering for scene
- [x] Show upload_max_filesize under Scene file to let user know their maximum file size allowed. Of course we still do valiate, but this message used for "warning" purpose.
- [ ] Character limit count under each input text. If reached limit then do not allow input anymore with notice message
- [ ] Reset password. Email ( SMTP ) must be worked before implement this feature
- [ ] Tours with ordering by Name / Created / Scenes / Hotspots

From @jooservices 
- [x] Add new button layout is broken.
- [x] Please move configuration to navigate bar same as Add new
- [x] Configuration is not working as expected. Tried to save the new value and it does not apply anything.
- [x] Also need configuration for social links: Facebook / Twitter / Google plus / Email
- [x] Please help me adding configuration for logo file. Allow upload logo or clear logo. Atm i have commented out show logo code line.
- [x] New toolbar ( save - save & close ) look little bit "unmatched" with global design. Please consider use same navigate
- [x] Notice message "Please upload logo to use feature Use logo" is not ready
- [x] Allow config via Configuration view, display user Logo as site logo or use default.

### CODE REVIEW

**Comment by jooservices** [comment]
Tour
	- Alias should be automate generate from Tour.name on even onBlur
	- Can not delete new Scene after added new one
Tour.edit
	- Can we allow to change ( reupload ) scene without delete and add new ?

General
	- Please use Assets class for adding css / js
Configuration
	- Use user logo
		Actually, we don't need this option. Explain this option:
			Each user ( usually a company ) can upload their logo and their company information via user profile view. If they have uploaded their logo, in scene.edit we show option: Use user logo to use this logo as "logo layer" on  Tour view ( frontend ).
	- KrPano path: Please change it into file input. So the user can easily choose krpano binary file ( instead of typing )
	- Close button on this view show at right side instead beside Save & Close

And please also help me check hotspot view.
- Go to hotspot view
- Add a hotspot
- Do not press save
- Go to next scene ( another scene )
- Add hotspot
- And now save
- We'll lost hotspot from first scene

**Comment by jooservices** [comment]
Please use Assets instead <script> or <style>.
Try to check with Url like
http://domain.com/abc/
Then you'll get issue

**Comment by jooservices** [comment]
image
Do delete scene if can't generate

**Comment by thongphp** [comment]
> - KrPano path: Please change it into file input. So the user can easily choose krpano binary file ( instead of typing )

Are you kidding me?

> - Can we allow to change ( reupload ) scene without delete and add new ?

Is that new feature request?

> - Please use Assets class for adding css / js

How to use? New class you just added?

**Comment by jooservices** [comment]
KrPano path: Please change it into file input. So the user can easily choose krpano binary file ( instead of typing )
Are you kidding me?
Never mind. We can ignore it and i will do it later

Is that new feature request?

Please use Assets class for adding css / js
How to use? New class you just added?
Not new feature. But fine. I will handle that. But careful when host site on sub directory. Your current code will be broken while including css / js

**Comment by thongphp** [comment]
Actually, we don't need this option. Explain this option:
> Each user ( usually a company ) can upload their logo and their company information via user profile view. If they have uploaded their logo, in scene.edit we show option: Use user logo to use this logo as "logo layer" on Tour view ( frontend ).
--> This feature is requested by you. https://github.com/jooservices/vr360.globalvision.dev/pull/299#discussion_r173648610
Now, it not actually needed :(

**Pull request merged**
